AllCops:
  TargetRubyVersion: 2.7.4
  NewCops: enable

# Don't fail for having too many tests
Metrics/BlockLength:
  AllowedMethods: ['describe']

Gemspec/RequireMFA:
  Enabled: false

require:
  - rubocop-rspec
  - rubocop-rake
